services:
  postgres:
    image: postgres:latest
    container_name: piscineds_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - piscineds_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  piscineds_data:
    name: piscineds_data
