SHELL := /bin/bash

.PHONY: clean ex00 ex01 ex02 ex03 ex04 ex05

clean:
	@rm -f ../Data/knight/Ex05_Training_knight.csv
	@rm -f ../Data/knight/Ex05_Validation_knight.csv

ex00:
	python3 ex00/histogram.py

ex01:
	python3 ex01/correlation.py

ex02:
	python3 ex02/points.py

ex03:
	python3 ex03/standardization.py

ex04:
	python3 ex04/normalization.py

ex05:
	python3 ex05/split.py